# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tips.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tips(object):
    def setupUi(self, Tips):
        Tips.setObjectName("Tips")
        Tips.resize(535, 349)
        Tips.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Tips)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Empezar = QtWidgets.QPushButton(Tips)
        self.pushButton_Empezar.setObjectName("pushButton_Empezar")
        self.gridLayout.addWidget(self.pushButton_Empezar, 1, 2, 1, 1)
        self.label_Tips = QtWidgets.QLabel(Tips)
        self.label_Tips.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"border:1px solid  #afaaf2;\n"
"border-radius:35;\n"
"padding:auto;")
        self.label_Tips.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Tips.setObjectName("label_Tips")
        self.gridLayout.addWidget(self.label_Tips, 0, 0, 1, 3)
        self.pushButton_Siguiente = QtWidgets.QPushButton(Tips)
        self.pushButton_Siguiente.setStyleSheet("border")
        self.pushButton_Siguiente.setObjectName("pushButton_Siguiente")
        self.gridLayout.addWidget(self.pushButton_Siguiente, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Tips)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Tips)
        self.pushButton_Empezar.clicked.connect(Tips.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Tips)

    def retranslateUi(self, Tips):
        _translate = QtCore.QCoreApplication.translate
        Tips.setWindowTitle(_translate("Tips", "Tips"))
        self.pushButton_Empezar.setText(_translate("Tips", "Empezar"))
        self.label_Tips.setText(_translate("Tips", "<html><head/><body><p><span style=\" font-size:medium; font-weight:600;\">Bienvenido a la plataforma de Testeo de SOFC.</span></p><p>Antes de empezar a usar el prgrama es necesario aprender<br/>algunas cosas. </p><ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Para el control de la plataforma hace falta realizar una conexión<br/>con el PLC. Esto se hace desde la barra de menú superior.</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Red--&gt;Conectar</span></li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Navegue por las diferentes secciones de la plataforma para<br/>controlar variables, elegir rutinas o analizar los datos mediante<br/>gráficos en tiempo real. </li></ol></body></html>"))
        self.pushButton_Siguiente.setText(_translate("Tips", "Siguiente tip"))
        self.checkBox.setText(_translate("Tips", "Mostrar al inicio"))
